name: Simple Test

on:
  workflow_dispatch:
    inputs:
      Target-Env:
        type: choice
        description: Target environment
        required: true
        options:
          - "dev"
          - "qa"
      setSecrets:
        type: boolean
        description: Set new secrets
        required: true
      key:
        type: string
        description: app id
        required: true
      deployS3Only:
        type: boolean
        description: deploy s3 only or deploy all other resourses
        required: true
jobs:
  infra-deployment:
    runs-on: ubuntu-latest
    env:
      Target: ${{ inputs.Target-Env }}
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run node
        run: npm run main
        env:
          App: testerMain
      
      - name: Deploy all resources
        run: echo "deploy s3 only not selected ${{ inputs.deployS3Only }}"
        if: ${{ !inputs.deployS3Only }}
      
      - name: Deploy only S3
        run: echo "deploy s3 only WAS selected ${{ inputs.deployS3Only }}"
        if: ${{ inputs.deployS3Only }}